run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - vet
    - gofmt
    - goimports
    - staticcheck
    - ineffassign
    - unused
    - deadcode

linters-settings:
  typecheck:
    check-blank: true
    check-nil: true

output:
  format: github-actions
