// Code generated by mockgen. DO NOT EDIT.

package mocks

import "net/http"

type MockHTTPClient struct {
	DoFunc func(req *http.Request) (*http.Response, error)
}

func (m *MockHTTPClient) Do(req *http.Request) (*http.Response, error) {
	if m == nil || m.DoFunc == nil {
		return nil, nil
	}
	return m.DoFunc(req)
}
